### ISSUE TITLE
Small issue with new log functionality (fix welcome)

### ISSUE THREAD

**Issue by skaman82** [skaman82/cleanflight-configurator#13]
"I did notice that the close operation isn't qiute right yet - when you open it, you get the log contents, if you scroll up to read something then close it, you don't get rescrolled to the last line - so see the first line instead. which given the ability to see only one line, seems like it should be the last notification."

**Comment by NightHawk32** [comment]
@skaman82 please give #51 a try.

**Comment by skaman82** [comment]
Thanks!
