### ISSUE TITLE
Generate a googlemap in GPS tab from GPS coordinates

### ISSUE THREAD

**Issue by skaman82** [skaman82/cleanflight-configurator#14]
<img width="165" alt="bildschirmfoto 2015-10-29 um 18 11 22" src="https://cloud.githubusercontent.com/assets/11768024/10826126/7ec2201c-7e68-11e5-8c18-4c1298baa9d0.png">
Thoughts:
1. Should check internet connection (if not present > info "no connection")
2. Should check GPS FIX state repeatedly (if not present > info "waiting for GPS Fix")
3. If fix is found > generate a map and show location (update the location repeatedly)

**Comment by skaman82** [comment]
Starting to work on this. Just added a connection test in the gps tab to check if the device is online to load a map.

**Comment by skaman82** [comment]
<img width="476" alt="bildschirmfoto 2015-11-19 um 14 14 36" src="https://cloud.githubusercontent.com/assets/11768024/11271683/f041d4fc-8ec7-11e5-8a85-32a752c05983.png">


Placed a map in the GPS tab (I get this to work only in a sandboxed iframe). This don't look nice at this state. I will style this after the function is ready. There will be external zoom controls also like in the screenshot at the top.

Tasks:
• LAT/LONG data should be passed to the map. If they change > map should be updated
• Map should only be visible if LAT/LONG (≠ 0). If LAT/LONG = 0  > show DIV with info "waiting for GPS Fix" 

As far I understand the LAT/LONG values should be passed with JSON or Chrome Message Passing. 

Here some sources:
http://stackoverflow.com/questions/7896480/get-access-to-google-maps-api-from-a-chrome-extension	
https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/sandbox
https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/sandboxed-content

**Comment by skaman82** [comment]
@NightHawk32 Can you please help me with this next? I prepared all the html/css stuff. This is the last main thing for the next PR. 

The LAT LOG coordinates are already there in the GPS Tab:
<img width="260" alt="bildschirmfoto 2015-11-25 um 14 15 06" src="https://cloud.githubusercontent.com/assets/11768024/11398122/eee0ce90-937e-11e5-9625-330172033eb7.png">

The new function should check if LAT/LONG ≠ 0 and then show the map and pass the new coordinates to it. This process should be a loop, so the map is refreshed if the coordinates change or will be hidden if the fix is lost.

**Comment by skaman82** [comment]
One more thing: tied to resize the custom map marker. But no luck so far. It should be approximately 20% - 30% smaller.
<img width="518" alt="bildschirmfoto 2015-11-25 um 14 22 08" src="https://cloud.githubusercontent.com/assets/11768024/11398333/3b0a4782-9380-11e5-8e25-367d705f82be.png">

**Comment by NightHawk32** [comment]
Please give #53 a try, and test if erverything works as espected.

**Comment by skaman82** [comment]
<img width="504" alt="bildschirmfoto 2015-12-02 um 02 01 32" src="https://cloud.githubusercontent.com/assets/11768024/11520649/a5c684ee-98a5-11e5-9a24-b9b761f49e95.png">

Found a small bug: If I cut the internet connection, the waiting animation is not hidden.

**Comment by skaman82** [comment]
done this! thanks @NightHawk32
