### ISSUE TITLE
Show profile selector in the header

### ISSUE THREAD

**Issue by skaman82** [skaman82/cleanflight-configurator#3]
TODO
<img width="222" alt="bildschirmfoto 2015-10-29 um 17 48 17" src="https://cloud.githubusercontent.com/assets/11768024/10825442/503c0616-7e65-11e5-9c1e-7a1de5b419eb.png">

**Comment by skaman82** [comment]
placed already in the header, but JS code is not working as it should. The profile switching is working but it should reload the current tab after switching. Can't figure that one out yet.

**Comment by skaman82** [comment]
@NightHawk32 maybe you could help solve this? I guess just view lines of code are missing or are wrong.

<img width="444" alt="bildschirmfoto 2015-11-16 um 13 06 30" src="https://cloud.githubusercontent.com/assets/11768024/11181505/e181dfdc-8c62-11e5-8926-b440cf0366a1.png">

Placed the dataflash  bar and profile switch in the header. The groundwork is already done for this (see new_stuff branch). Here the problems I can not solve:

• Somehow the dataflash and profile status getting updated only on the SECOND connection attempt.
• Dataflash should show the div .noflash and hide div .dataflash-contents if dataflash is not supported
• Profile switch changes the profile but it seems to do it several times. 
• After changing the profile the current tab should be reinitialised
• I also see several MSP timeouts - what is causing this?

Placed the JS code in serial_backend.js for now, but I'm sure it has to go in main.js or in gui.js and should be triggered on connect in serial_backend.js

**Comment by NightHawk32** [comment]
I will have a look at it this evening. I'm currently at work.

**Comment by NightHawk32** [comment]
@skaman82 please have a look at #47 this should be done now.

**Comment by skaman82** [comment]
@NightHawk32 Thanks a lot! closing this!
