### ISSUE TITLE
Sensors panel not showing up in header after connect for some boards

### ISSUE THREAD

**Issue by wanderzell** [skaman82/cleanflight-configurator#37]
Everything works ok as long as I test with my **Naze32 Acro rev5** - after connect the device/port selection is replaced with the sensors panel.

However, with **Naze32 Acro rev6** and **Sparky1.1** there are no sensors shown in the header, just device/port selections.

Is it some known issue, being fixed, or should I take a look at it?

**Comment by skaman82** [comment]
have only couple of naze32 boards here to test. Didn't heard of this issue before. I this bug also in current master?

**Comment by wanderzell** [comment]
Haven't checked with master. I can do it.

**Comment by skaman82** [comment]
@wanderzell
Seems strange to me. I didn't change any code regarding hardware. 

I also noticed that some other issues came up after the merge with development branch. Mybee you can look at this also.

• Dominic said that JS code for switchery buttons and tooltips had to go in the main.js file. This has some unwanted consequences. In some tabs like Ports and Configuration where the page rebuilds after board reboot the toggle switches and tooltips disappear.

• The Tooltip icon in the config tab is behaving strangely (remains green after hover). In the pid tab it does what it should.

**Comment by wanderzell** [comment]
Okay. I will take a look.

**Comment by skaman82** [comment]
@wanderzell you can leave the first mentioned bug in the message above alone, @hydra fixed this by himself. Sadly he fixed also some other things we were working on without giving us a heads up. That results in some waisted hours of our quality time and duplicate work :( @hydra: This should be coordinated better in the future, don't you think?

**Comment by skaman82** [comment]
@hydra Ohh, just saw you din't fix as many things as I thought. Mainly just the toggle buttons and JS problem in the tabs. So not much wasted time at all :) The toggle buttons in the ports tab are to big in your fix. There should be medium sized buttons (see my PR for that)

**Comment by wanderzell** [comment]
Thanks :) Just finished fixing some of mentioned things: https://github.com/wanderzell/cleanflight-configurator/commit/4b732ae87ef7aa30ed6e49b59eb8f4f1b38e4447

**Comment by skaman82** [comment]
I'm sorry for that :(

**Comment by skaman82** [comment]
thanks for fixing this!

**Comment by wanderzell** [comment]
@skaman82 @hydra would it be better for me to work and do PR directly against cleanflight/cleanflight-configurator repository rather than skaman82/cleanflight-configurator? what is current status of main repository, do you have the GUI-rework already merged, or is it still work in progress?

**Comment by skaman82** [comment]
@wanderzell The first stage is already merged with master and the new version got released yesterday. I'm waiting for the merge of our small bugfixes into dev branch. If you want to debug the current code it would be better if you work direct against main dev branch. 

I want to add new features to my GUI rework like profile switch and dataflash bar in the header. For that I might need some help with JS if you can afford the time. For that it would be nice if your working against my branch.
