### ISSUE TITLE
Sensor Orientation selector

### ISSUE THREAD

**Issue by NightHawk32** [skaman82/cleanflight-configurator#39]
Selecting the flight controller orientation via Cli is qite a bit confusing sometimes. This could be a lot easier with a nice dropdown menu and a little image showing the chosen direction. I can do the firmware things and the JS but it would be nice if someone did the graphics and a layout how to visualize it best.

**Comment by skaman82** [comment]
I can do the graphics and the CSS stuff :)

**Comment by skaman82** [comment]
You don't have to do it in the CLI actually. The is a section for that in the Config tab. But it could be done nicer with supporting images. 
<img width="501" alt="bildschirmfoto 2015-11-18 um 23 45 18" src="https://cloud.githubusercontent.com/assets/11768024/11256825/738b3b16-8e4e-11e5-9a08-8b556d221123.png">

**Comment by NightHawk32** [comment]
Ah yes thanks, I have to admit that I have never tried that. I was thinking about the align gyro and align ACC features of the Cli. So I will try to figure out the difference between these two options.
But although we could predefine some orientations.

**Comment by skaman82** [comment]
Align mag should be also there

**Comment by skaman82** [comment]
This is how this could look like:
<img width="435" alt="bildschirmfoto 2015-11-19 um 15 40 07" src="https://cloud.githubusercontent.com/assets/11768024/11273498/e4aca1b0-8ed3-11e5-8f1b-73d25b35d59b.png">

**Comment by skaman82** [comment]
prepared the tab elements

<img width="526" alt="bildschirmfoto 2015-12-06 um 15 32 07" src="https://cloud.githubusercontent.com/assets/11768024/11613808/899e1af2-9c2e-11e5-8bbb-46775bde30d0.png">

**Comment by skaman82** [comment]
moving this to PR3 milestone. This basically adds new input fields like a bunch of other stuff we are making in PR3. This way we keep many things together that require a API bump.

**Comment by skaman82** [comment]
just added a tooltip 
<img width="662" alt="bildschirmfoto 2015-12-10 um 12 59 30" src="https://cloud.githubusercontent.com/assets/11768024/11714913/eb47f914-9f3d-11e5-977d-fcfc12f80443.png">

**Comment by skaman82** [comment]
CW0_DEG=1, CW90_DEG=2, CW180_DEG=3, CW270_DEG=4, CW0_DEG_FLIP=5, CW90_DEG_FLIP=6, CW180_DEG_FLIP=7, CW270_DEG_FLIP=8. This should cover all orientations.

**Comment by skaman82** [comment]
Hmmmm. set align_mag = 3 don't work anymore. Nothing in the docs :( @digitalentity do you now how this works now?

**Comment by digitalentity** [comment]
Now it's `set align_mag = CW180_DEG`

**Comment by skaman82** [comment]
thanks! and when it is upsidedown?

**Comment by digitalentity** [comment]
CW180_DEG_FLIP, was 7 on older firmwares

**Comment by digitalentity** [comment]
You already covered all options here: https://github.com/skaman82/cleanflight-configurator/issues/39#issuecomment-164201243

**Comment by skaman82** [comment]
ok, thanks

**Comment by skaman82** [comment]
Thanks @NightHawk32
