### ISSUE TITLE
Add deadband and yaw_deadband settings

### ISSUE THREAD

**Issue by skaman82** [skaman82/cleanflight-configurator#61]
I think the should go here in the Receiver Tab:
<img width="497" alt="bildschirmfoto 2015-12-07 um 02 56 22" src="https://cloud.githubusercontent.com/assets/11768024/11617380/456a8b1c-9c8e-11e5-853e-0313ddc386a3.png">

**Comment by skaman82** [comment]
just added this

<img width="529" alt="bildschirmfoto 2015-12-07 um 03 06 20" src="https://cloud.githubusercontent.com/assets/11768024/11617450/9aa6aec0-9c8f-11e5-9f70-f8f4dff63a57.png">

**Comment by skaman82** [comment]
decided to move the new fields from the right (they have nothing to do with the graph) and placed them above the channels
<img width="551" alt="bildschirmfoto 2015-12-07 um 03 24 34" src="https://cloud.githubusercontent.com/assets/11768024/11617655/494e97a6-9c92-11e5-9f3c-644880800c90.png">

**Comment by NightHawk32** [comment]
We should think about a proper way to hide the Yaw Deadband and Deadband input fields. This is necesarry for API levels which don't support the MSP command to get the data.

**Comment by skaman82** [comment]
you are right, didn’t thought of that. Will place the fields somewhere else (easier to hide)


> Am 09.12.2015 um 23:07 schrieb NightHawk32 <notifications@github.com>:
> 
> We should think about a proper way to hide the Yaw Deadband and Deadband input fields. This is necesarry for API levels which don't support the MSP command to get the data.
> 
>

**Comment by skaman82** [comment]
done

**Comment by NightHawk32** [comment]
Thanks for the quick fix, this made the whole thing much easier.

**Comment by skaman82** [comment]
done, we can close this
