### ISSUE TITLE
Add PID Filters to the PID Tab

### ISSUE THREAD

**Issue by skaman82** [skaman82/cleanflight-configurator#62]
Fields:
acc_lpf_factor
gyro_lpf
gyro_cut_hz
pterm_cut_hz
dterm_cut_hz

**Comment by skaman82** [comment]
added placeholders

<img width="538" alt="bildschirmfoto 2015-12-08 um 12 13 41" src="https://cloud.githubusercontent.com/assets/11768024/11654341/2fbacba2-9da5-11e5-9c74-8c30bf8f4b61.png">

**Comment by skaman82** [comment]
@borisbstyle Could you please provide a small text for the Tooltips explaining how to configure _cut_hz Filter and what this does?

**Comment by skaman82** [comment]
restyled the right side of the tab completely. Can't get the Rates and TPA to save yet.

![bildschirmfoto 2015-12-08 um 13 48 25](https://cloud.githubusercontent.com/assets/11768024/11655999/69e2c64c-9db2-11e5-8737-c1a08c894db4.png)

**Comment by skaman82** [comment]
@borisbstyle Some feedback on my question regarding the tooltips?

**Comment by skaman82** [comment]
Removing this for now. This makes the interface more complicated as it should be.

**Comment by borisbstyle** [comment]
i agree. Filtering will be changed in the future anyway
Op 12 dec. 2015 23:49 schreef "Albert Kravcov" <notifications@github.com>:
