### ISSUE TITLE
New LED function - Show GPS 3D fix status 

### ISSUE THREAD

**Issue by skaman82** [skaman82/cleanflight-configurator#67]

**Comment by skaman82** [comment]
@NightHawk32 Do you have some time to look into this one in the next weeks? Perhaps it would also be great to add a beacon function (white flashing light) to use as position lights on a plane or multirotor?

**Comment by digitalentity** [comment]
@skaman82 I like your suggestion:

> What do you think of that?
> No fix = red LED flashing
> 2D fix = yellow LED flashing
> 3D fix = green LED always on

But why discussing LEDs in Configurator issue? :)

**Comment by skaman82** [comment]
@digitalentity This issue tracker is not configurator only. Its a issue/wish list from me and nighthawk32 regarding new things to do :) It is easier to keep it in one place. BTW: Enhanced LED functionality needs some changes in the GUI too.

**Comment by digitalentity** [comment]
Ah, yes, forgot about the configuring the LEDs. BTW, current Cleanflight doesn't distinguish between 2D and 3D fix, only iNav will have that in release 1.2 (or maybe in 1.1.2 as well)

**Comment by skaman82** [comment]
@gaelj you've done some work on LED functionality in the past days. 
Could you please add some more LED functions if you have time? 

For example: 
• 3Dfix status (see comments above)
• Beacon (the LED flashes in selected color - helpful for position lights)
Both features should be added to LED Tab as well.

**Comment by gaelj** [comment]
I'll look into it, I'll be unavailable next week though.

**Comment by digitalentity** [comment]
@skaman82 
I've done some rework to GPS tab here https://github.com/iNavFlight/inav-configurator
It relies on an INAV-specific MSP message though.
