### ISSUE TITLE
Make save buttons stick to the bottom of the #content element

### ISSUE THREAD

**Issue by skaman82** [skaman82/cleanflight-configurator#7]
The idea is to keep the save button always visible and in the same place independent from the length of the content (scrolling). Tried to get this done with my limited skills for the last four hours - no success.  Would appreciate some help on this.
<img width="970" alt="bildschirmfoto 2015-10-29 um 17 10 37" src="https://cloud.githubusercontent.com/assets/11768024/10825656/51631fa6-7e66-11e5-8b46-f1fa82ff84cb.png">

**Comment by wanderzell** [comment]
You can assign it to me.

**Comment by skaman82** [comment]
@wanderzell  Great! Please let me know when you figure this out.

**Comment by wanderzell** [comment]
Please look into PR #25 
There are styles for sticky toolbar as well as for one that anchors into bottom edge, but is not always visible - behaviour can be set through .toolbar_fixed_bottom and .toolbar_scroll_bottom classes on the tab container elements.
Also did some clean-up on the tab html files to remove the duplicate button styling, so all this is now in main.css. Some tabs required minor rework on the layouts, but as far as I tested (on Mac) everything seemed working ok.

**Comment by skaman82** [comment]
thanks
